#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
from lxml import etree
import json
import re
import requests
testdata={
	"sEcho": 1,
	"iTotalRecords": 832,
	"iTotalDisplayRecords": 832,
	"aaData": [
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515494\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515494\">蹉跎.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515494);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515494);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515494);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515494);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515494);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515494);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "4.05 MB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515486\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515486\">村夫野话录.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515486);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515486);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515486);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515486);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515486);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515486);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "325.48 KB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515483\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515483\">催眠二十八讲.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515483);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515483);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515483);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515483);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515483);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515483);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "322.38 KB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515479\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515479\">崔玉涛：宝贝健康公开课.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515479);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515479);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515479);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515479);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515479);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515479);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "2.28 MB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515473\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515473\">崔永元：我有一事，生死与之 (中国故事).azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515473);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515473);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515473);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515473);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515473);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515473);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "1 KB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515467\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515467\">从战争中走来：两代军人的对话.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515467);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515467);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515467);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515467);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515467);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515467);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "1.32 MB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515464\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515464\">从一元一次方程到伽罗瓦理论.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515464);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515464);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515464);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515464);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515464);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515464);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "2.01 MB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515453\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515453\">从野蛮到精细：2012-2021中国房地产未来十年（中国故事）.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515453);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515453);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515453);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515453);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515453);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515453);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "2.15 MB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515446\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515446\">从台北到北京：胡同台妹眼中的大陆.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515446);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515446);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515446);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515446);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515446);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515446);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "1.52 MB", "6 小时前", "VIP永久"],
		["<label class=\"pos-rel\"><input type='checkbox' name=\"file_ids[]\" value=\"302515444\"  class=\"ace\" \/><span class=\"lbl\"><\/span><\/label>", "\t\t\t\t\t<div class=\"pull-left\">\r\n\t\t\t\t\t<i class=\"fileicon fileicon-other\"><\/i> <a target=\"_blank\" href=\"https:\/\/jackmk.ctfile.com\/fs\/14155983-302515444\">从你的全世界路过（完美升级版）.azw3<\/a>\r\n\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<div class=\"pull-right\">\r\n\t\t\t\t\t\t<div class=\"position-relative file-control-icon\">\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515444);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock bigger-130 grey\" data-rel=\"tooltip\" title=\"允许所有用户浏览\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515444);\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt bigger-130 grey\" data-rel=\"tooltip\" title=\"获取分享链接\" ><\/i>\r\n\t\t\t\t\t\t\t<\/a>\r\n\r\n\t\t\t\t\t\t\t<div class=\"pull-right pos-rel dropdown-hover\" style=\"margin-left: 20px;\">\r\n\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-cog bigger-130 pointer blue\"><\/i>\r\n\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-only-icon dropdown-light dropdown-caret dropdown-close dropdown-menu-right\">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_modify(302515444);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"green\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-edit green\"><\/i> 修改文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_share(302515444);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"orange\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-share-alt orange\"><\/i> 获取分享链接\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_lock(302515444);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"blue\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-lock blue\"><\/i> 访问密码\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\r\n\t\t\t\t\t\t\t\t\t<li>\r\n\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete(302515444);\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"red\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-trash red\"><\/i> 删除文件\r\n\t\t\t\t\t\t\t\t\t\t\t<\/span>\r\n\t\t\t\t\t\t\t\t\t\t<\/a>\r\n\t\t\t\t\t\t\t\t\t<\/li>\r\n\t\t\t\t\t\t\t\t<\/ul>\r\n\t\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t\t<\/div>\r\n\t\t\t\t\t<\/div>", "1.36 MB", "6 小时前", "VIP永久"]
	]
}




# return json.dumps(r.json())
    
def httprequest(pageindex):
    headers = {'Accept':'application/json, text/javascript, */*; q=0.01',
    'Accept-Encoding':'gzip, deflate, br',
    'Accept-Language':'zh-CN,zh;q=0.9',
    'Connection':'keep-alive',
    'Cookie':'_ga=GA1.2.1132044206.1498442329; ct_uid=b59dee7d431666d87f63d07e0879a1da; clicktopay=1533204576412; hibext_instdsigdip=1; ua_checkmutilogin=oNoaB5TuM1; pubcookie=VjFSZwE8AmIAMFY7UT5aMgVeUGlRDVdqBzZTY1U0VDlQbQIKBGsFOANjV20LOwUqWmdWOAY0UDEEZlE2UWlUZVYyUloBdAIyAHBWbFFhWmkFNlAiUXJXZQcuU0BVOFQ5UGcCagRkBX4DZVdsCzEFV1o5VmMGYFA0BGFRMFFrVGBWNlJmAQQCYgBgVjNRMVpkBWJQNlEzVzEHblM1VT1UZVA3AjUEOQViA2VXNAs-BW9aalYyBjVQYgQxUTVRPVQxVmNSYwFr; hibext_instdsigdipv2=1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
    'X-Requested-With': 'XMLHttpRequest'
    }
    iDisplayStart=(pageindex - 1)*100
    payload={
    'item': 'file_act',
    'action': 'file_list',
    'folder_id': 29335756,
    'task': 'index',
    'sEcho': pageindex,
    'iColumns': 5,
    'sColumns': ',,,,',
    'iDisplayStart': iDisplayStart,
    'iDisplayLength': 100,
    'mDataProp_0': 0,
    'sSearch_0': '',
    'bRegex_0': 'false',
    'bSearchable_0': 'true',
    'bSortable_0': 'false',
    'mDataProp_1': 1,
    'sSearch_1': '',
    'bRegex_1': 'false',
    'bSearchable_1': 'true',
    'bSortable_1': 'true',
    'mDataProp_2': 2,
    'sSearch_2': '',
    'bRegex_2': 'false',
    'bSearchable_2': 'true',
    'bSortable_2': 'true',
    'mDataProp_3': 3,
    'sSearch_3': '',
    'bRegex_3': 'false',
    'bSearchable_3': 'true',
    'bSortable_3': 'true',
    'mDataProp_4': 4,
    'sSearch_4': '',
    'bRegex_4': 'false',
    'bSearchable_4': 'true',
    'bSortable_4': 'true',
    'sSearch': '',
    'bRegex': 'false',
    'iSortingCols': 0,
    '_': 1533714140931
    }
    r = requests.get('https://home.ctfile.com/iajax.php', params=payload,headers=headers)
    r.encoding='utf-8'
    dataobj=r.json()
    # print dataobj
    return dataobj
    # print(r.json().decode('unicode_escape'))

#https://segmentfault.com/q/1010000006053119

def lxmlHtml(html):
    con = etree.HTML(html)
    # print(etree.tostring(con, encoding="gb2312", pretty_print=True, method="html"))
    # print(etree.tostring(con))
    mages =  con.xpath('//div[@class="pull-left"]/a/text()')
    herf =  con.xpath('//div[@class="pull-left"]/a/@href')
    # mages =  con.xpath('//div/i[@fileicon-other]/a/text()')
    return json.dumps({'title':mages[0],'herf':herf}, encoding='UTF-8', ensure_ascii=False)


def  getHtmlvalue(html):
#https://www.cnblogs.com/hhh5460/p/5079465.html
    con = etree.HTML(html)
    # print(etree.tostring(con))
    value =  con.xpath('//input/@value')
    return value[0]
booklist = []    
def init():
    
    dataobj=httprequest(1)
    applyData(dataobj)
    totalNum = dataobj['iTotalRecords']
    totalPage = totalNum/100
    if(totalNum%100 > 0):
        totalPage+=1
    for num in range(2,totalPage+1):
        applyData(httprequest(num))

    with open("./book.json",'w') as f:
        json.dump(booklist,f)



def applyData(data):
    for test in data["aaData"]:
        # html1=re.sub('[\r\n\t]', '', test[0])
        # html1.replace("\\","")
        # numno=getHtmlvalue(html1)
        # print(numno)
        html2=re.sub('[\r\n\t]', '', test[1])
        html2.replace("\\","")
        # json.dumps(html2, encoding='UTF-8', ensure_ascii=False)
        title = lxmlHtml(html2)
        booklist.append(json.loads(title))
      
def init2():
    with open("./book.json",'r') as load_f:
        load_list = json.load(load_f)
        print len(load_list)
        for book in load_list:
            print json.dumps(book, encoding='UTF-8', ensure_ascii=False)

        


init2()       